import { QueryClient, QueryClientProvider, useQuery } from '@tanstack/react-query';
import type { Account, AddonContext, AddonEnableFunction } from '@wealthfolio/addon-sdk';
import { useEffect, useMemo, useRef, useState } from 'react';
import '@wealthfolio/ui/styles';
import { authenticate, getMonetaryAccounts, getPayments, loadAccountSettings, loadConfig, paymentActivity, paymentCategory, saveAccountSettings, saveConfig, wealthfolioAccountPayload, type BunqAccountSettings, type BunqConfig, type BunqMonetaryAccount } from './bunq';

let addonCtx: AddonContext | undefined;
type SyncProgress = { phase: string; current: number; total: number; created: number; imported: number; errors: number; done: boolean };
const accountTypeLabel = (type?: string) => ({ 'monetary-account-bank': 'Bankrekening', 'monetary-account-savings': 'Spaarrekening', 'monetary-account-joint': 'Gezamenlijke rekening', 'monetary-account-external': 'Externe rekening', 'monetary-account-external-savings': 'Externe spaarrekening', 'monetary-account-card': 'Kaartrekening', 'monetary-account': 'Overig' }[type ?? 'monetary-account'] ?? type ?? 'Overig');
const mergeSettings = (accounts: BunqMonetaryAccount[], settings: Record<string, BunqAccountSettings>) => Object.fromEntries(accounts.map((account) => [String(account.id), { ...settings[String(account.id)], sync: settings[String(account.id)]?.sync ?? true }]));
const accountType = (account: BunqMonetaryAccount) => account.accountType ?? 'monetary-account';
const groupAccounts = (accounts: BunqMonetaryAccount[]) => [...new Set(accounts.map(accountType))].sort().map((type) => ({ type, accounts: accounts.filter((account) => accountType(account) === type).sort((a, b) => (a.description ?? '').localeCompare(b.description ?? '') || a.id - b.id) }));

function CategorySyncCheckbox({ label, allSelected, someSelected, onChange }: { label: string; allSelected: boolean; someSelected: boolean; onChange: (checked: boolean) => void }) {
  const checkboxRef = useRef<HTMLInputElement>(null);
  useEffect(() => {
    if (checkboxRef.current) checkboxRef.current.indeterminate = someSelected;
  }, [someSelected]);
  return <input ref={checkboxRef} type="checkbox" aria-label={label} checked={allSelected} onChange={(e) => onChange(e.target.checked)} />;
}

function Progress({ progress }: { progress: SyncProgress }) {
  const percent = progress.total ? Math.min(100, Math.round((progress.current / progress.total) * 100)) : 0;
  return <section className="border rounded-lg p-4 space-y-2" aria-label="Sync voortgang"><div className="flex justify-between text-sm"><strong>{progress.done ? 'Sync afgerond' : progress.phase}</strong><span>{progress.current}/{progress.total} accounts · {percent}%</span></div><div className="h-3 w-full rounded bg-muted overflow-hidden"><div className="h-full bg-primary transition-all" style={{ width: `${percent}%` }} /></div><div className="text-sm text-muted-foreground">{progress.created} accounts toegevoegd · {progress.imported} transacties geïmporteerd{progress.errors ? ` · ${progress.errors} fouten` : ''}</div></section>;
}

function AccountControls({ account, settings, categories, update }: { account: BunqMonetaryAccount; settings: BunqAccountSettings; categories: Awaited<ReturnType<AddonContext['api']['spending']['getCategories']>>; update: (id: number, patch: Partial<BunqAccountSettings>) => void }) {
  const options = (kind: 'expense' | 'income') => categories.filter((item) => item.kind === kind);
  return <div className="border rounded p-3 space-y-2"><div className="flex items-start justify-between gap-3"><div><strong>{account.description || `bunq account ${account.id}`}</strong><div className="text-sm text-muted-foreground">{accountTypeLabel(account.accountType)} · {account.balance?.value ?? '—'} {account.balance?.currency ?? account.currency ?? ''} · ID {account.id}</div></div><label className="text-sm flex items-center gap-2"><input type="checkbox" checked={settings.sync} onChange={(e) => update(account.id, { sync: e.target.checked })} /> Syncen</label></div><div className="grid grid-cols-1 md:grid-cols-2 gap-2"><label className="text-sm">Fallback expense<select className="border border-input bg-background text-foreground rounded px-2 py-1 w-full" value={settings.expenseCategory ?? ''} onChange={(e) => update(account.id, { expenseCategory: e.target.value || undefined })}><option value="">Geen fallback</option>{options('expense').map((item) => <option value={item.key} key={item.key}>{item.path || item.name}</option>)}</select></label><label className="text-sm">Fallback income<select className="border border-input bg-background text-foreground rounded px-2 py-1 w-full" value={settings.incomeCategory ?? ''} onChange={(e) => update(account.id, { incomeCategory: e.target.value || undefined })}><option value="">Geen fallback</option>{options('income').map((item) => <option value={item.key} key={item.key}>{item.path || item.name}</option>)}</select></label></div></div>;
}

function BunqWizard({ accounts, settings, categories, autoAdd, setAutoAdd, setSettings, onFinish, onSave, onCancel }: { accounts: BunqMonetaryAccount[]; settings: Record<string, BunqAccountSettings>; categories: Awaited<ReturnType<AddonContext['api']['spending']['getCategories']>>; autoAdd: boolean; setAutoAdd: (value: boolean) => void; setSettings: (value: Record<string, BunqAccountSettings>) => void; onFinish: () => void; onSave: () => void; onCancel: () => void }) {
  const grouped = useMemo(() => groupAccounts(accounts), [accounts]);
  const [expanded, setExpanded] = useState<Record<string, boolean>>(() => Object.fromEntries(grouped.map(({ type }) => [type, false])));
  const update = (id: number, patch: Partial<BunqAccountSettings>) => setSettings({ ...settings, [String(id)]: { ...settings[String(id)], ...patch, sync: patch.sync ?? settings[String(id)]?.sync ?? true } });
  const setCategorySync = (items: BunqMonetaryAccount[], sync: boolean) => setSettings({ ...settings, ...Object.fromEntries(items.map((account) => [String(account.id), { ...settings[String(account.id)], sync }])) });
  return <section className="fixed inset-0 z-10 bg-background text-foreground overflow-auto p-6" aria-label="bunq configuratiewizard"><div className="max-w-5xl mx-auto space-y-5"><header><p className="text-sm text-primary">Stap 2 van 2</p><h2 className="text-2xl font-bold">bunq accounts configureren</h2><p className="text-muted-foreground">Kies per rekeningtype welke accounts naar Wealthfolio mogen en stel fallbackcategorieën in.</p></header>{grouped.map(({ type, accounts: items }) => { const isExpanded = expanded[type] ?? false; const selectedCount = items.filter((account) => settings[String(account.id)]?.sync ?? true).length; const allSelected = selectedCount === items.length; const someSelected = selectedCount > 0 && !allSelected; const categoryId = `bunq-category-${type.replace(/[^a-zA-Z0-9_-]/g, '-')}`; return <section className="border rounded-lg p-3 space-y-2" key={type}><div className="flex items-center justify-between gap-3"><button type="button" className="flex items-center gap-2 text-left" aria-expanded={isExpanded} aria-controls={categoryId} onClick={() => setExpanded((current) => ({ ...current, [type]: !isExpanded }))}><span aria-hidden="true" className="text-lg leading-none">{isExpanded ? '⌄' : '›'}</span><span className="text-lg font-semibold">{accountTypeLabel(type)} ({items.length})</span></button><label className="text-sm flex items-center gap-2"><CategorySyncCheckbox label={`Alle ${accountTypeLabel(type)} synchroniseren`} allSelected={allSelected} someSelected={someSelected} onChange={(sync) => setCategorySync(items, sync)} /> Alles selecteren</label></div>{isExpanded && <div id={categoryId} className="space-y-2">{items.map((account) => <AccountControls key={account.id} account={account} settings={settings[String(account.id)] ?? { sync: true }} categories={categories} update={update} />)}</div>}</section>; })}<section className="border rounded-lg p-4 space-y-2"><h3 className="font-semibold">Nieuwe bunq accounts</h3><label className="flex gap-2 items-start"><input type="checkbox" checked={autoAdd} onChange={(e) => setAutoAdd(e.target.checked)} /><span><strong>Nieuwe accounts automatisch toevoegen</strong><br /><span className="text-sm text-muted-foreground">Uitgeschakeld: nieuwe accounts verschijnen eerst alleen in deze wizard.</span></span></label></section><div className="flex flex-wrap gap-2"><button className="rounded px-4 py-2 bg-primary text-primary-foreground" onClick={onFinish}>Opslaan en sync starten</button><button className="border border-input bg-background rounded px-4 py-2" onClick={onCancel}>Annuleren</button><button className="border border-input bg-background rounded px-4 py-2" onClick={onSave}>Opslaan en terug naar overzicht</button></div></div></section>;
}

function BunqPage({ ctx }: { ctx: AddonContext }) {
  const [config, setConfig] = useState<BunqConfig | null>(null); const [baseUrl, setBaseUrl] = useState<BunqConfig['baseUrl']>('https://api.bunq.com'); const [apiKey, setApiKey] = useState(''); const [message, setMessage] = useState(''); const [accountSettings, setAccountSettings] = useState<Record<string, BunqAccountSettings>>({}); const [wizardOpen, setWizardOpen] = useState(false); const [wizardSettings, setWizardSettings] = useState<Record<string, BunqAccountSettings>>({}); const [wizardAutoAdd, setWizardAutoAdd] = useState(false); const [progress, setProgress] = useState<SyncProgress | null>(null);
  useEffect(() => { void Promise.all([loadConfig(ctx), loadAccountSettings(ctx)]).then(([stored, settings]) => { setAccountSettings(settings); if (stored) { setConfig(stored); setBaseUrl(stored.baseUrl); } }).catch((error: unknown) => ctx.api.logger.error(`Unable to load bunq configuration: ${String(error)}`)); }, [ctx]);
  const accounts = useQuery<Account[]>({ queryKey: ['wealthfolio-accounts'], queryFn: () => ctx.api.accounts.getAll() }); const bunqAccounts = useQuery({ queryKey: ['bunq-accounts', config], queryFn: () => getMonetaryAccounts(ctx, config!), enabled: Boolean(config), staleTime: 60_000 }); const spendingCategories = useQuery({ queryKey: ['bunq-spending-categories'], queryFn: () => ctx.api.spending.getCategories(), enabled: Boolean(config), staleTime: 300_000 }); const categories = spendingCategories.data ?? [];
  const activeAccounts = useMemo(() => (bunqAccounts.data ?? []).filter((account) => accountSettings[String(account.id)]?.sync ?? true), [bunqAccounts.data, accountSettings]);
  const groupedActiveAccounts = useMemo(() => groupAccounts(activeAccounts), [activeAccounts]);
  const updateAccountSetting = (id: number, patch: Partial<BunqAccountSettings>) => { const current = accountSettings[String(id)]; const next = { ...accountSettings, [String(id)]: { ...current, ...patch, sync: patch.sync ?? current?.sync ?? true } }; setAccountSettings(next); void saveAccountSettings(ctx, next).catch((error: unknown) => setMessage(`Accountinstelling opslaan mislukt: ${String(error)}`)); };
  useEffect(() => { if (wizardOpen && bunqAccounts.data && Object.keys(wizardSettings).length === 0) setWizardSettings(mergeSettings(bunqAccounts.data, accountSettings)); }, [wizardOpen, bunqAccounts.data, accountSettings, wizardSettings]);
  const connect = async () => { if (!apiKey.trim()) { setMessage('Vul je bunq API-key in.'); return; } try { const next = await authenticate(ctx, baseUrl, apiKey.trim()); const safeNext = { ...next, autoAddNewAccounts: false }; await saveConfig(ctx, safeNext); setConfig(safeNext); setApiKey(''); setWizardAutoAdd(false); setWizardSettings({}); setWizardOpen(true); setMessage('API-koppeling geslaagd. Configureer nu je accounts.'); } catch (error) { setMessage(`Verbinden mislukt: ${String(error)}`); } };
  const sync = async (forceCreate = false, settingsOverride = accountSettings, configOverride = config) => { if (!configOverride || !bunqAccounts.data) return; const available = bunqAccounts.data; const selected = available.filter((a) => settingsOverride[String(a.id)]?.sync ?? true); const total = selected.length; let current = 0; setProgress({ phase: 'Accounts voorbereiden', current: 0, total, created: 0, imported: 0, errors: 0, done: false }); const existing = accounts.data ?? []; const map = new Map(existing.filter((item) => item.provider === 'bunq' && item.providerAccountId).map((item) => [item.providerAccountId!, item])); let created = 0; const canCreate = forceCreate || configOverride.autoAddNewAccounts !== false; for (const account of selected) { const id = String(account.id); if (existing.some((item) => item.provider === 'bunq' && item.providerAccountId === id)) continue; if (!canCreate) { ctx.api.logger.info(`bunq account ${id} awaits manual wizard selection`); continue; } try { map.set(id, await ctx.api.accounts.create(wealthfolioAccountPayload(account))); created += 1; } catch (error) { ctx.api.logger.error(`bunq account creation failed for ${id}: ${String(error)}`); } } const refetched = await accounts.refetch(); for (const account of (refetched.data ?? accounts.data ?? [])) if (account.provider === 'bunq' && account.providerAccountId) map.set(account.providerAccountId, account); let imported = 0; let errors = 0; const rules = new Map<string, { ruleKey: string; name: string; pattern: string; kind: 'expense' | 'income'; categoryId: string; accountId: string; priority: number }>(); let spending = categories; try { spending = await ctx.api.spending.getCategories(); } catch (error) { ctx.api.logger.warn(`bunq could not load spending categories: ${String(error)}`); } const normalize = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim(); const findCategory = (value: string, kind: 'expense' | 'income') => { const wanted = normalize(value); const candidates = spending.filter((item) => item.kind === kind); return candidates.find((item) => normalize(item.key) === wanted || normalize(item.name) === wanted || normalize(item.path) === wanted) ?? candidates.find((item) => normalize(item.path).includes(wanted) || wanted.includes(normalize(item.name))); };
    for (const account of selected) { current += 1; const settings = settingsOverride[String(account.id)] ?? { sync: true }; setProgress({ phase: `Transacties ophalen: ${account.description || account.id}`, current, total, created, imported, errors, done: false }); const wf = map.get(String(account.id)); if (!wf) continue; try { const existingActivities = await ctx.api.activities.getAll(wf.id); const existingIds = new Set(existingActivities.flatMap((item) => [item.sourceRecordId, item.idempotencyKey, item.comment?.match(/\[bunq-payment:(\d+)\]/)?.[1]].filter(Boolean).map(String))); const payments = await getPayments(ctx, configOverride, account.id); const imports = payments.filter((payment) => !existingIds.has(String(payment.id))).map((payment) => { const activityType = paymentActivity(payment, wf.id, wf.name).activityType; const kind = ['CREDIT', 'DEPOSIT', 'TRANSFER_IN', 'INTEREST'].includes(activityType) ? 'income' : 'expense'; return paymentActivity(payment, wf.id, wf.name, paymentCategory(payment) || (kind === 'income' ? settings.incomeCategory : settings.expenseCategory)); }); for (const payment of payments) { const activityType = paymentActivity(payment, wf.id, wf.name).activityType; const kind = ['CREDIT', 'DEPOSIT', 'TRANSFER_IN', 'INTEREST'].includes(activityType) ? 'income' : 'expense'; const category = paymentCategory(payment) || (kind === 'income' ? settings.incomeCategory : settings.expenseCategory); const description = payment.description?.trim(); const match = category && findCategory(category, kind); if (!match || !description) continue; const base = `${kind}:${match.categoryId}:${wf.id}:${description}`; rules.set(`${base}:description`, { ruleKey: `bunq-${base}`, name: `bunq: ${category} (${description})`, pattern: description, kind, categoryId: match.categoryId, accountId: wf.id, priority: 90 }); rules.set(`${base}:marker`, { ruleKey: `bunq-${base}-marker`, name: `bunq: ${category}`, pattern: `[bunq-category:${category}]`, kind, categoryId: match.categoryId, accountId: wf.id, priority: 100 }); } if (imports.length) imported += (await ctx.api.activities.import(imports)).summary.imported; } catch (error) { errors += 1; ctx.api.logger.error(`bunq transaction sync failed for account ${account.id}: ${String(error)}`); } }
    for (const rule of rules.values()) try { await ctx.api.spending.saveRule(rule); } catch (error) { ctx.api.logger.warn(`bunq could not save category rule '${rule.name}': ${String(error)}`); } if (rules.size) await ctx.api.spending.rerunRules(true); ctx.api.query.invalidateQueries(['activities']); setProgress({ phase: 'Sync afgerond', current: total, total, created, imported, errors, done: true }); setMessage(`${created} nieuwe accounts en ${imported} transacties geïmporteerd${errors ? `; ${errors} fouten` : ''}.`); };
  const startWizard = () => { setWizardSettings(mergeSettings(bunqAccounts.data ?? [], accountSettings)); setWizardAutoAdd(config?.autoAddNewAccounts ?? false); setWizardOpen(true); }; const saveWizard = (startSync: boolean) => { const next = { ...config!, autoAddNewAccounts: wizardAutoAdd }; setAccountSettings(wizardSettings); setConfig(next); void Promise.all([saveAccountSettings(ctx, wizardSettings), saveConfig(ctx, next)]).then(() => { setWizardOpen(false); if (startSync) void sync(true, wizardSettings, next); }).catch((error: unknown) => setMessage(`Wizard opslaan mislukt: ${String(error)}`)); }; const finishWizard = () => saveWizard(true); const saveWizardOverview = () => saveWizard(false);
  return <main className="p-6 max-w-5xl mx-auto space-y-6">
    <header><h1 className="text-3xl font-bold">bunq Accounts</h1><p className="text-muted-foreground">Importeer en synchroniseer bunq monetary accounts in Wealthfolio.</p></header>
    <section className="border rounded-lg p-5 space-y-3">
      <h2 className="text-lg font-semibold">Stap 1 · API-koppeling</h2><p className="text-sm text-muted-foreground">Voer alleen je bunq API-key in. De addon voert de installatie-, device- en session-bootstrap uit.</p>
      <select className="border rounded px-3 py-2 w-full" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value as BunqConfig['baseUrl'])}><option value="https://api.bunq.com">Production</option><option value="https://public-api.sandbox.bunq.com">Sandbox</option></select>
      <input className="border rounded px-3 py-2 w-full" placeholder="bunq API-key" type="password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} /><button className="border rounded px-3 py-2" onClick={() => void connect()}>Opslaan & verbinden</button>
    </section>
    {config && <section className="border rounded-lg p-5 space-y-3">
      <div className="flex justify-between items-center gap-3"><h2 className="text-lg font-semibold">Accounts</h2><div className="flex gap-2"><button className="border rounded px-3 py-2" onClick={startWizard} disabled={bunqAccounts.isLoading}>Wizard opnieuw doorlopen</button><button className="border rounded px-3 py-2" onClick={() => void sync()} disabled={bunqAccounts.isLoading || Boolean(progress && !progress.done)}>Sync starten</button></div></div>
      <p className="text-sm text-muted-foreground">{config.autoAddNewAccounts === false ? 'Nieuwe accounts worden handmatig via de wizard toegevoegd.' : 'Nieuwe accounts worden automatisch toegevoegd.'}</p>
      {bunqAccounts.isLoading && <p>Accounts laden…</p>}{bunqAccounts.error && <p className="text-red-600">{String(bunqAccounts.error)}</p>}{progress && <Progress progress={progress} />}
      {!bunqAccounts.isLoading && !bunqAccounts.error && groupedActiveAccounts.length === 0 && <div className="border border-dashed rounded-lg p-4 space-y-2"><p className="font-medium">Geen actieve bunq accounts</p><p className="text-sm text-muted-foreground">Voeg accounts toe of activeer ze opnieuw via de wizard.</p></div>}
      {groupedActiveAccounts.map(({ type, accounts: items }) => <section className="border rounded-lg p-3 space-y-2" key={type}><h3 className="text-lg font-semibold">{accountTypeLabel(type)} ({items.length})</h3>{items.map((account) => <AccountControls key={account.id} account={account} settings={accountSettings[String(account.id)] ?? { sync: true }} categories={categories} update={updateAccountSetting} />)}</section>)}
    </section>}
    {message && <p role="status">{message}</p>}
    {wizardOpen && bunqAccounts.data && <BunqWizard accounts={bunqAccounts.data} settings={wizardSettings} categories={categories} autoAdd={wizardAutoAdd} setAutoAdd={setWizardAutoAdd} setSettings={setWizardSettings} onFinish={finishWizard} onSave={saveWizardOverview} onCancel={() => setWizardOpen(false)} />}
  </main>;
}

const BunqRoute = () => <QueryClientProvider client={addonCtx!.api.query.getClient() as QueryClient}><BunqPage ctx={addonCtx!} /></QueryClientProvider>;
const enable: AddonEnableFunction = async (ctx) => { addonCtx = ctx; const stored = await loadConfig(ctx); if (stored) ctx.api.logger.info('bunq configuration loaded'); ctx.router.add({ id: 'bunq-accounts', path: '/addons/bunq-addon', component: BunqRoute }); ctx.onDisable(() => { addonCtx = undefined; }); };
export default enable;
